### ISSUE TITLE
Validation fails because of missing fields

### ISSUE THREAD

**Issue by Franklin89** [TelegramBots/Telegram.Bot.Extensions.LoginWidget#4]
https://github.com/TelegramBots/Telegram.Bot.Extensions.LoginWidget/blob/59ea03c65fb2ac44be0312e07d6eb775f9b8e65a/src/Telegram.Bot.Extensions.LoginWidget/LoginWidget.cs#L51

I tried to use this extension but it will not work. From the Login Widget I only get 4 fields: `id`, `first_name`, `auth_date` and the `hash`.

I checked the user has no username set. And also no last name.

**Comment by MihaZupan** [comment]
Thank you for the report.

I will update the requirements. Would be nice if telegram noted what fields are actually mandatory.

**Comment by MihaZupan** [comment]
Fixed in NuGet 1.2.0
Now only `id`, `auth_date` and `hash` are counted as mandatory.
